Feature/42269 d365 payload key configuration changes
UKHO/external-notification-service pull request #20
Opened 2022-02-17 07:43 UTC by vipin14904

1. Removed D365PayloadKeyConfiguration class and added D365PayloadKeyConstant class for constant variable as per suggestion. 

2. Rename Topic name from "fss-filesPublished" to "fss-filesPublished-AvcsData" NotificationTypes.json

2022-02-18 13:26 UTC, usha13529 requested changes
Please fix minor review comments.

2022-02-18 13:26 UTC, usha13529 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.UnitTests/Services/SubscriptionServiceTest.cs
>      {
Remove unused Using & Sort Usings

2022-02-18 13:26 UTC, usha13529 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.UnitTests/Validation/D365PayloadValidatorTest.cs
>      {
Remove unused Using & Sort Usings

2022-02-18 13:26 UTC, usha13529 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API/Services/SubscriptionService.cs
>      {
Remove unused Using & Sort Usings

2022-02-18 13:26 UTC, usha13529 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API/Validation/D365PayloadValidator.cs
>      public class D365PayloadValidator : AbstractValidator<D365Payload>, ID365PayloadValidator
Remove unused Using & Sort Usings

2022-02-18 13:26 UTC, usha13529 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.Common/Configuration/D365PayloadKeyConstant.cs
> +    {
Make class static

2022-02-18 14:11 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.UnitTests/Services/SubscriptionServiceTest.cs
>      {
Changes are done as requested.

2022-02-18 14:11 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.UnitTests/Validation/D365PayloadValidatorTest.cs
>      {
Changes are done as requested.

2022-02-18 14:11 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API/Services/SubscriptionService.cs
>      {
Changes are done as requested

2022-02-18 14:11 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API/Validation/D365PayloadValidator.cs
>      public class D365PayloadValidator : AbstractValidator<D365Payload>, ID365PayloadValidator
Changes are done as requested

2022-02-18 16:36 UTC, usha13529 approved these changes
LGTM

2022-02-21 08:40 UTC, barrie-cooper approved these changes
All good thanks

2022-02-21 08:40 UTC, merged