24167 ens handle mapping of the scs event to catalogue notification
UKHO/external-notification-service pull request #45
Opened 2022-03-24 05:31 UTC by ganpat-tech

PR contain  code changes, unit test cases and Function test cases.

2022-03-24 14:09 UTC, usha13529 requested changes
Few minor comments to fix please.

2022-03-24 14:27 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.FunctionalTests/D365PayloadTestData/D365ScsSamplePayload.json
> +                "Id": "bd0ccbc8-2975-ec11-8943-002248818243",
Changes done

2022-03-24 14:27 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.FunctionalTests/FunctionalTests/EnsEnterpriseEventServiceWebhookTest.cs
> +        private ScsEventData ScsEventData { get; set; }
Removed

2022-03-24 14:35 UTC, vipin14904 commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.FunctionalTests/Helper/ScsEventDataBase.cs
> +        public static ScsEventData GetScsEventData()
Done

2022-03-25 05:35 UTC, usha13529 approved these changes
Thanks for the changes. LGTM.

2022-03-25 06:59 UTC, ganpat-tech commented on UKHO.ExternalNotificationService.API/UKHO.ExternalNotificationService.API.FunctionalTests/FunctionalTests/EnsEnterpriseEventServiceWebhookTest.cs
> +        public async Task WhenICallTheEnsWebhookApiWithAValidScsJObjectBody_ThenOkStatusIsReturned()
Thanks For highlighting , done changes.

2022-03-25 11:24 UTC, barrie-cooper approved these changes
LGTM

2022-03-25 11:24 UTC, merged